// src/components/App.vue
<template>
	<Page>
		<ActionBar title="Welcome to NativeScript-Vue!" />
		<StackLayout>
			<Button :text="msg" @tap="showModal" />
		</StackLayout>
	</Page>
</template>

<script lang="ts">
import Vue from 'nativescript-vue'
import { Component } from 'vue-property-decorator'
import ExoPlayerModal from '~/exoplayer/ExoPlayerModal.vue'

// @ts-ignore
@Component
export default class App extends Vue {
	msg = 'Show ExoPlayerModal'
	mounted() {
		// setTimeout(() => this.showModal(), 1000)
	}
	showModal() {
		this.$showModal(ExoPlayerModal as any, {
			cancelable: false,
			fullscreen: true,
		})
	}
}
</script>

<style scoped>
ActionBar {
	background-color: #53ba82;
	color: #ffffff;
}

.message {
	vertical-align: center;
	text-align: center;
	font-size: 20px;
	color: #333333;
}
</style>

// src/components/App.svelte
<script lang="typescript">
	import ExoPlayerModal from '~/exoplayer/ExoPlayerModal.svelte'
	import { showModal } from 'svelte-native'

	function launchModal() {
		showModal({
			page: ExoPlayerModal,
			fullscreen: true,
			stretched: true,
			animated: true,
			android: { cancelable: false },
		})
	}

	let message = 'Blank Svelte Native App'
</script>

<style>
</style>

<page>
	<actionBar title="Svelte Native App" />
	<stackLayout>
		<label horizontalAlignment="center" verticalAlignment="middle" text={message} />
		<button text="Open Modal" on:tap={launchModal} />
	</stackLayout>
</page>
